package rpc;

/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2024-11-12")
public class MinMaxPair implements org.apache.thrift.TBase<MinMaxPair, MinMaxPair._Fields>, java.io.Serializable, Cloneable, Comparable<MinMaxPair> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MinMaxPair");

  private static final org.apache.thrift.protocol.TField MIN_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("minValue", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField MAX_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("maxValue", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new MinMaxPairStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new MinMaxPairTupleSchemeFactory();

  public int minValue; // required
  public int maxValue; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MIN_VALUE((short)1, "minValue"),
    MAX_VALUE((short)2, "maxValue");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MIN_VALUE
          return MIN_VALUE;
        case 2: // MAX_VALUE
          return MAX_VALUE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __MINVALUE_ISSET_ID = 0;
  private static final int __MAXVALUE_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MIN_VALUE, new org.apache.thrift.meta_data.FieldMetaData("minValue", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.MAX_VALUE, new org.apache.thrift.meta_data.FieldMetaData("maxValue", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MinMaxPair.class, metaDataMap);
  }

  public MinMaxPair() {
  }

  public MinMaxPair(
    int minValue,
    int maxValue)
  {
    this();
    this.minValue = minValue;
    setMinValueIsSet(true);
    this.maxValue = maxValue;
    setMaxValueIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MinMaxPair(MinMaxPair other) {
    __isset_bitfield = other.__isset_bitfield;
    this.minValue = other.minValue;
    this.maxValue = other.maxValue;
  }

  @Override
  public MinMaxPair deepCopy() {
    return new MinMaxPair(this);
  }

  @Override
  public void clear() {
    setMinValueIsSet(false);
    this.minValue = 0;
    setMaxValueIsSet(false);
    this.maxValue = 0;
  }

  public int getMinValue() {
    return this.minValue;
  }

  public MinMaxPair setMinValue(int minValue) {
    this.minValue = minValue;
    setMinValueIsSet(true);
    return this;
  }

  public void unsetMinValue() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __MINVALUE_ISSET_ID);
  }

  /** Returns true if field minValue is set (has been assigned a value) and false otherwise */
  public boolean isSetMinValue() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __MINVALUE_ISSET_ID);
  }

  public void setMinValueIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __MINVALUE_ISSET_ID, value);
  }

  public int getMaxValue() {
    return this.maxValue;
  }

  public MinMaxPair setMaxValue(int maxValue) {
    this.maxValue = maxValue;
    setMaxValueIsSet(true);
    return this;
  }

  public void unsetMaxValue() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __MAXVALUE_ISSET_ID);
  }

  /** Returns true if field maxValue is set (has been assigned a value) and false otherwise */
  public boolean isSetMaxValue() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __MAXVALUE_ISSET_ID);
  }

  public void setMaxValueIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __MAXVALUE_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case MIN_VALUE:
      if (value == null) {
        unsetMinValue();
      } else {
        setMinValue((java.lang.Integer)value);
      }
      break;

    case MAX_VALUE:
      if (value == null) {
        unsetMaxValue();
      } else {
        setMaxValue((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case MIN_VALUE:
      return getMinValue();

    case MAX_VALUE:
      return getMaxValue();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case MIN_VALUE:
      return isSetMinValue();
    case MAX_VALUE:
      return isSetMaxValue();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof MinMaxPair)
      return this.equals((MinMaxPair)that);
    return false;
  }

  public boolean equals(MinMaxPair that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_minValue = true;
    boolean that_present_minValue = true;
    if (this_present_minValue || that_present_minValue) {
      if (!(this_present_minValue && that_present_minValue))
        return false;
      if (this.minValue != that.minValue)
        return false;
    }

    boolean this_present_maxValue = true;
    boolean that_present_maxValue = true;
    if (this_present_maxValue || that_present_maxValue) {
      if (!(this_present_maxValue && that_present_maxValue))
        return false;
      if (this.maxValue != that.maxValue)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + minValue;

    hashCode = hashCode * 8191 + maxValue;

    return hashCode;
  }

  @Override
  public int compareTo(MinMaxPair other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetMinValue(), other.isSetMinValue());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMinValue()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.minValue, other.minValue);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetMaxValue(), other.isSetMaxValue());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMaxValue()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.maxValue, other.maxValue);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("MinMaxPair(");
    boolean first = true;

    sb.append("minValue:");
    sb.append(this.minValue);
    first = false;
    if (!first) sb.append(", ");
    sb.append("maxValue:");
    sb.append(this.maxValue);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'minValue' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'maxValue' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MinMaxPairStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public MinMaxPairStandardScheme getScheme() {
      return new MinMaxPairStandardScheme();
    }
  }

  private static class MinMaxPairStandardScheme extends org.apache.thrift.scheme.StandardScheme<MinMaxPair> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, MinMaxPair struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MIN_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.minValue = iprot.readI32();
              struct.setMinValueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MAX_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.maxValue = iprot.readI32();
              struct.setMaxValueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetMinValue()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'minValue' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetMaxValue()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'maxValue' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, MinMaxPair struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(MIN_VALUE_FIELD_DESC);
      oprot.writeI32(struct.minValue);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(MAX_VALUE_FIELD_DESC);
      oprot.writeI32(struct.maxValue);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MinMaxPairTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public MinMaxPairTupleScheme getScheme() {
      return new MinMaxPairTupleScheme();
    }
  }

  private static class MinMaxPairTupleScheme extends org.apache.thrift.scheme.TupleScheme<MinMaxPair> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MinMaxPair struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI32(struct.minValue);
      oprot.writeI32(struct.maxValue);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MinMaxPair struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.minValue = iprot.readI32();
      struct.setMinValueIsSet(true);
      struct.maxValue = iprot.readI32();
      struct.setMaxValueIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

